### ISSUE TITLE
[Feature Request] Markdown Literary programming that don't break the syntax of any programming language

### ISSUE THREAD

**Issue by linpengcheng** [mohzy83/NppMarkdownPanel#1]
# Markdown Literary programming that don't break the syntax of any programming language

## comment area markup method:

Just add a custom line comment character before each line of Markdown.

In the comments of code, you can draw flowcharts, tasklist, display data visualizations, etc.

When previewing or converting a format, you only need to simply preprocess: replace the `\r\n\;` with `\r\n`

Note: 

- line comment character of Clojure(Lisp) is `;`
- line breaks and line comment  characters of the current file can be obtained from the editor's API.

when we edit the code, we can preview the effect in real time. 
Editing literary code has a live preview panel like most markdown editors.

## The editor has a Live Preview panel to do the following work:

1. Get the current text 

2. replace the `\r\n\;` with `\r\n`

3. live Preview markdown string

4. Easily export directly to PDF or HTML.

## Its advantages:

1. It don't break the syntax of any programming language, you can compile directly. comment area markup method can be applied to any programming language and any markup (including Org,rst, asciidoc, etc.), which is the greatest advantage.

2. you only need a single line of regular replacement preprocessing, then you can use any Markdown parse or converter.

3. Support any code editor that supports Markdwon Live preview, allowing the source code of any programming language to become rich text in real time. In the code's comment area, You can use the markdown to draw flowcharts, tables, task lists, and display images on the live preview panel, enhance the readability of your code.

4. If you extend the Markdwon tag, you can implement the eval code, print result, display data visualization and other instruction tags, to achieve live programming, live test.

## example:

```clojure
;### Markdown literary programming
;#### example01:
;```clojure
(defn f [[evens odds total amax amin] x]
  (let [[evens odds] (cond 
                       (even? x) [(inc evens ) odds]
                       (odd? x)  [evens (inc odds)]
                       :else     [evens odds])
        total (+ total x)
        amax  (max amax x)
        amin  (min amin x)]   
     [evens odds total amax amin]))
;;The comment of the code requires at least two line comment characters
(reduce f [0 0 0 ##-Inf ##Inf] [5 6 8 -3 -9 11 156 6 7])
;```
;return`[4 5 187 156 -9]`

```

## Live Preview Effects:

> 
> ### Markdown literary programming
> #### example01:
> ```clojure
> (defn f [[evens odds total amax amin] x]
>   (let [[evens odds] (cond 
>                        (even? x) [(inc evens ) odds]
>                        (odd? x)  [evens (inc odds)]
>                        :else     [evens odds])
>         total (+ total x)
>         amax  (max amax x)
>         amin  (min amin x)]   
>      [evens odds total amax amin]))
> ;The comment of the code requires at least two line comment characters
> (reduce f [0 0 0 ##-Inf ##Inf] [5 6 8 -3 -9 11 156 6 7])
> ```
> return`[4 5 187 156 -9]`
>

**Comment by mohzy83** [comment]
Hi,
thanks for the suggestion, the plugin is using [CommonMark.NET](https://github.com/Knagis/CommonMark.NET) to convert markdown files to html. CommonMark.NET is 100% CommonMark Spec compliant and the feature you have suggested is not implemented by CommonMark.NET. I dont think the plugin should handle any additional markdown parsing, therefor please file a feature request for [CommonMark.NET](https://github.com/Knagis/CommonMark.NET) if you think this is important.

**Comment by linpengcheng** [comment]
Thank you for your reply!

If you let the plug-in judge that the file extension is not  `. MD` or `. markdown`:

1. Gets the current file text.
2. get  the line breaks and line comment char of the current file by notepad++ API.
3. Regular expressions replace  "line breaks and line comment char (for example, in C # is: `\r\n\\\\`)" with "line breaks(`\r\n`)" ,  then get standard Markdwon text.
```csharp
//reference MarkdownViewer.cs, AbstractRenderer.cs
using System.Text.RegularExpressions;
editor = new ScintillaGateway(PluginBase.GetCurrentScintilla());
txt = editor.GetText(editor.GetLength() + 1);
txt = Replace(txt, "\r\n\\\\","\r\n");
Markdig.Markdown.ToHtml(text, this.markdownPipeline);
```
4. Parse with Markdown Library 
5. preview.

**Comment by linpengcheng** [comment]
Now, I have [a temporary NPP solution and patch](https://github.com/linpengcheng/PurefunctionPipelineDataflow/blob/master/doc/markdown_literary_programming.md#NotepadPlusPlus-Solutions).
