### ISSUE TITLE
Table format is not working

### ISSUE THREAD

**Issue by gn4711** [mohzy83/NppMarkdownPanel#11]
No table format is happening. 
Tested from documentation something like this:

- Markdown | Less | Pretty
- --- | --- | ---
- *Still* | `renders` | **nicely**
- 1 | 2 | 3

or this

- |a |b | 
- |b |c |

but nothing is happening (samples taken from the markdig)

**Comment by famod** [comment]
Do you mean tables are not rendered _at all_? If yes: I cannot confirm this, works for me (npp 7.7 and NppMarkdownPanel 0.4).

**Comment by AakaFosfor** [comment]
I can confirm, that in NPP 7.7 and NMP 0.3 tables were not working at all. In NMP 0.4 they are rendered properly (I've just updated).

**Comment by mohzy83** [comment]
Thats right you need at least version 0.4 of NMP, to render tables.
