### ISSUE TITLE
Default to previous zoom level

### ISSUE THREAD

**Issue by JWoolley-FL-USA** [mohzy83/NppMarkdownPanel#12]
I find this plugin very useful. When I first open the panel, I find the default zoom level is too high. I can adjust the zoom level by use of Ctrl+MouseWheel. But the next time I start Notepad++ and open the panel, my previous zoom level is not restored. Is there a way to save my previous zoom level as the new default level? Or can you set the default zoom so normal text appears approximately the same size in both panels?

**Comment by mohzy83** [comment]
There is a new option in plugin version 0.5.0 which allows to set the zoomlevel to a custom value.
This value is persistent and will be applied next time you start npp.
