### ISSUE TITLE
Synchronize and Align Viewer With Caret

### ISSUE THREAD

**Issue by JWoolley-FL-USA** [mohzy83/NppMarkdownPanel#14]
I find the option to synchronize the NppMarkdownPanel's viewer with Npp's caret useful, but it would be more useful if the viewer maintained vertical alignment with the caret. Currently the caret's associated text is always positioned at the top of the viewer. Is it possible to _actually_ synchronize the viewer with the caret, including vertical alignment? If not, perhaps you could position the caret's associated text from 35% to 50% below the top of the viewer, so it can be seen in context with other nearby text.

**Comment by evan-king** [comment]
Better yet, how about synchronizing the scrolling itself, so that _top_ of the rendered content starts with the same line that's at the top of the editor's text view?

**Comment by mohzy83** [comment]
There is a new feature in version 0.7.1 which addresses this issue.
The Option is called "https://github.com/mohzy83/NppMarkdownPanel/releases/tag/0.7.1"
