### ISSUE TITLE
[Feature Request] Support mermaidjs

### ISSUE THREAD

**Issue by linpengcheng** [mohzy83/NppMarkdownPanel#2]
Support mermaidjs 
[https://github.com/mermaidjs](https://github.com/mermaidjs)

**Comment by mohzy83** [comment]
Digrams are currently not supported by CommonMark.NET. I checked all .NET markdown parsers with diagram support and i found [markdig
](https://github.com/lunet-io/markdig).  That lib has diagram support. I will try to integrate that in one of the next releases.

**Comment by linpengcheng** [comment]
Thank you, Digrams is a useful tool for programmers.

**Comment by mohzy83** [comment]
This should work now with the new release 0.4.0. The new Version is using Markdig as renderer, which supports diagrams.
