### ISSUE TITLE
[Feature Request] Select/follow active editor pane.

### ISSUE THREAD

**Issue by evan-king** [mohzy83/NppMarkdownPanel#20]
Currently when Notepad++ is using dual editor panes, the markdown panel (on the right) always renders the contents of the text pane on the left, with the other text pane dividing down the middle.

I would like the option to render contents of the panel currently in focus, and/or configure which static choice of panel will always be rendered.

**Comment by fortunewalla** [comment]
Same here. I have dual panes divided by horizontal line i.e. top and bottom parts. The plugin preview the tab selected in the top pane even if the active (currently in focus) tab is in the bottom pane.

**Comment by mohzy83** [comment]
I can reproduce the issue -> will fix it in the next release.

**Comment by mohzy83** [comment]
Bug has been fixed in version 0.7.1 https://github.com/mohzy83/NppMarkdownPanel/releases/tag/0.7.1
