### ISSUE TITLE
[bug] line seperator in conjunction with heading

### ISSUE THREAD

**Issue by DJCrashdummy** [mohzy83/NppMarkdownPanel#21]
it seems to be a kind of a follow up to #4... but definitively something weird is going on:

"heading2" (no matter if you use `##` before or `---` underneath) gets underlined... some phraser underline "heading1" and "heading2", but according to [CommonMark](https://spec.commonmark.org/dingus/) no heading is underlined by default!

so either "heading1" **and** "heading2" should be underlined or none, which is IMHO the correct resp. better choice because you can still ad a line separator (`---`) if you want to.

**Comment by mohzy83** [comment]
This is an issue with the default style (from github) -> heading have an underline
Please select another css if you dont like that style.
![grafik](https://user-images.githubusercontent.com/26003088/96248666-313ffa00-0fac-11eb-8af8-e64af1756fb3.png)
