### ISSUE TITLE
Can't be uninstalled via plugins admin

### ISSUE THREAD

**Issue by ZwergNaseXXL** [mohzy83/NppMarkdownPanel#24]
- install NppMarkdownPanel
- open plugins admin, go to "Installed" tab
- check "Markdown Panel", press "Remove" button
- "Npp is about to exit" message box pops up, click "yes"
- admin password prompt pops up, enter admin password (I'm on a non-admin account)
- Npp is restarted, NppMarkdownPanel is still there
- rinse & repeat

Expectation: NppMarkdownPanel is uninstallable via Npp's plugins admin.

**Comment by phisad** [comment]
As a workaround, simply remove the NppMarkdownPanel directory from your NPP plugins dir.

**Comment by mohzy83** [comment]
The uninstall using the plugin-admin is working for me.
Can you check again with a current npp version?

**Comment by ZwergNaseXXL** [comment]
I just re-installed this plugin and then tried to uninstall it, still doesn't work for me. Notepad++ 7.9, NppMarkdownPanel 0.5.0. Note that I'm on a non-admin account. There is an admin credential prompt when I try to uninstall it, but it doesn't seem to help. When I delete the plugin folder, I have to provide admin credentials too, but that works. So I guess the problem is related to file permissions.

**Comment by mohzy83** [comment]
@ZwergNaseXXL , do you still have issues uninstalling the plugin?

**Comment by ZwergNaseXXL** [comment]
No, I just tested it and it works fine with current versions.

**Comment by sunwapta** [comment]
I also cannot uninstall Markdown Panel from the plugin Admin (using steps as listed in the original post above) Using latest version of notepad++ 8.6.8 64-bit.   So used the workaround of manually deleting the markdowns plugin directory.
