### ISSUE TITLE
Support for Latex equations?

### ISSUE THREAD

**Issue by czdiao** [mohzy83/NppMarkdownPanel#25]
Hi! I am a user of this nice plugin and I quite like it. I am using the latest version 0.5.0 on windows 10. However, I find it is not supporting the math equations using simple Latex syntax on my computer. I use this feature quite often as my markdown files contain a lot of Greek letters and math equations.

Is this feature supported in this plugin? If not, is it possible for you to add it? Or is there any way that I can make it work on my computer?

Thanks a lot!
William

**Comment by mohzy83** [comment]
Thats beyond the scope of this plugin. Just create images from those equations and embed them into your markdown file.

**Comment by andrzejQ** [comment]
I think it is working:
https://github.com/andrzejQ/NppMarkdownPanel/tree/RegExp/NppMarkdownPanel/Resources/_posts
"2018-11-06-Test-MD-TeX2jax.md"

**Comment by asmwarrior** [comment]
> I think it is working: https://github.com/andrzejQ/NppMarkdownPanel/tree/RegExp/NppMarkdownPanel/Resources/_posts "2018-11-06-Test-MD-TeX2jax.md"

Hi, can you explain how to do that inside the Notepad++ editor. 

Do I need to directly download the md file you mentioned, 

~~~~
https://raw.githubusercontent.com/andrzejQ/NppMarkdownPanel_RegExp_arch/RegExp/NppMarkdownPanel/Resources/_posts/2018-11-06-Test-MD-TeX2jax.md
~~~~

and open it under Notepad++ with NppNarkdownPanel enabled?

Thanks.

**Comment by andrzejQ** [comment]
`Resources/nppMdP.tests/Test-MD-TeX2jax.md`  - `[Download row file]` and open it in N++. It is working with MarkdownPanel 7.3+

<https://github.com/andrzejQ/NppMarkdownPanel_RegExp_arch/blob/RExp072/NppMarkdownPanel/Resources/nppMdP.tests/Test-MD-TeX2jax.md>

**Comment by asmwarrior** [comment]
> `Resources/nppMdP.tests/Test-MD-TeX2jax.md` - `[Download row file]` and open it in N++. It is working with MarkdownPanel 7.3+
> 
> https://github.com/andrzejQ/NppMarkdownPanel_RegExp_arch/blob/RExp072/NppMarkdownPanel/Resources/nppMdP.tests/Test-MD-TeX2jax.md

Hi, thanks for the reply. Unluckily, I already did that, but that dose not work because in my Windows 7 64bit system, it jumps some message box saying that the script has some errors and can't be executed. I checked that my OS has IE8 as the web browser.

**Comment by andrzejQ** [comment]
Maybe download older binaries and replace them in
`c:\Program Files\Notepad++\plugins\NppMarkdownPanel\`

**Comment by mohzy83** [comment]
Please run this command with cmd.exe :
`reg query "HKEY_LOCAL_MACHINE\Software\Microsoft\Internet Explorer" /v svcVersion`
This should print your current IE version.
You need at least IE 11...
