### ISSUE TITLE
[Feature Request] Send to Printer

### ISSUE THREAD

**Issue by InmobAli** [mohzy83/NppMarkdownPanel#26]
Is it possible to add the print feature to send the rendered content to the printer?

Thanks a lot!

**Comment by Fromax** [comment]
> Is it possible to add the print feature to send the rendered content to the printer?

Right-click somewhere in the rendered content and choose "Print..." :wink:

**Comment by mohzy83** [comment]
Hi,
this should already work.
Try right click in the view.
There should be a "print"-entry in the context menu.
I get this (its in german "Drucken.." for "Print")
![grafik](https://user-images.githubusercontent.com/26003088/96241771-e8377800-0fa2-11eb-9dc0-1efbda2d4853.png)
