### ISSUE TITLE
Footnotes don't work

### ISSUE THREAD

**Issue by CapinWinky** [mohzy83/NppMarkdownPanel#28]
If you click a footnote or the return, it tries to open the Microsoft store.

**Comment by mohzy83** [comment]
This issue should be fixed with the new markdig 0.30 version in release 0.7.0.

**Comment by mohzy83** [comment]
issue can be reproduced

**Comment by mohzy83** [comment]
Bug has been fixed in version 0.7.1 https://github.com/mohzy83/NppMarkdownPanel/releases/tag/0.7.1
