### ISSUE TITLE
Inline CSS support?

### ISSUE THREAD

**Issue by CapinWinky** [mohzy83/NppMarkdownPanel#29]
With https://github.com/nea/MarkdownViewerPlusPlus, I can give elements a CSS ID and then modify them inline.

~~~
## Using CSS for Custom Formatting! {#MyCustom-ID}

<Style>
	#MyCustom-ID {
            background-color: orange;
			text-decoration: underline;
			color: darkslategray;
         }
</Style>
~~~

Since that project is not maintained, I was thinking of moving to this one (especially since this one renders checklists and image hover text properly), but I used that custom CSS stuff on occasion and really like it.

**Comment by mohzy83** [comment]
Please use a css-class instead of an id to style elements.
See:
![grafik](https://user-images.githubusercontent.com/26003088/96247955-191bab00-0fab-11eb-97d5-07bcf4b2b2f3.png)
