### ISSUE TITLE
html export. Links become absolute, not relative

### ISSUE THREAD

**Issue by Pinballl** [mohzy83/NppMarkdownPanel#31]
Tested the html export in 0.5.1.3.
Links in he exported html file gets the absolute paths of the links instead of the relative paths.

br

**Comment by mohzy83** [comment]
How do you export to html?

**Comment by Pinballl** [comment]
Hi,
I used this version; 0.5.1.3.  Maybe it's an unofficial fork? I'm not too familiar with programmeing/github.
There it is a buttton for export to html.


Best regards
TJ

[cid:3f1b4cc4-bb8f-44ad-be92-5b68a3a5d0da]


https://github.com/andrzejQ/NppMarkdownPanel/releases/download/v0.5.1.3/NppMarkdownPanel-0.5.1.3.zip

https://github.com/andrzejQ/NppMarkdownPanel/releases/
[https://avatars0.githubusercontent.com/u/36765728?s=400&v=4]<https://github.com/andrzejQ/NppMarkdownPanel/releases/>
Releases · andrzejQ/NppMarkdownPanel<https://github.com/andrzejQ/NppMarkdownPanel/releases/>
Lightweight Notepad++ plugin to preview Markdown files. Releases -> - andrzejQ/NppMarkdownPanel
github.com


________________________________
Fra: Moritz Hzy <notifications@github.com>
Sendt: fredag 2. oktober 2020 21:14
Til: mohzy83/NppMarkdownPanel <NppMarkdownPanel@noreply.github.com>
Kopi: Pinballl <ioslo@hotmail.com>; Author <author@noreply.github.com>
Emne: Re: [mohzy83/NppMarkdownPanel] html export. Links become absolute, not relative (#31)


How do you export to html?

**Comment by mohzy83** [comment]
I have integrated the pullrequest which added the "export"-function. 
will try to fix the issue ...

**Comment by mohzy83** [comment]
This one is fixed in release 0.6.1
When you use the "save" function, no absolute path is saved anymore.
