### ISSUE TITLE
Single line breaks aren't rendered as new lines

### ISSUE THREAD

**Issue by PetbkA** [mohzy83/NppMarkdownPanel#32]
![notepad++_2020-10-13_19-04-23](https://user-images.githubusercontent.com/22843816/96240508-a9f18700-0fa9-11eb-98f1-0a245ff590eb.png)

Only double line breaks renders as new line.

Problem doesn't depend on line break types (i.e. Windows (CR LF), Unix (LF), Mac (CR)).

**Plugin version:** 0.5.0

**Comment by mohzy83** [comment]
Hi,
this is default markdown behaviour.
https://www.markdownguide.org/basic-syntax#line-breaks
You have to add 2 or more spaces at the end and you will get the linebreak:
![grafik](https://user-images.githubusercontent.com/26003088/96241240-2ed8a280-0fa2-11eb-9ea6-53f516bdb31a.png)

**Comment by keith555** [comment]
It would be good to have an option to respect linebreaks regardless of the number of spaces. Both the VSCode Markdown Preview Enhanced plugin and Typora break lines regardless of the number of spaces at the end of the line.

**Comment by SaturnusDJ** [comment]
> It would be nice to have an option to respect linebreaks regardless of the number of spaces.

I would like this too, because Github Markdown behaves like that.
