### ISSUE TITLE
[Feature Request]: add option to hide panel on every opened file

### ISSUE THREAD

**Issue by PetbkA** [mohzy83/NppMarkdownPanel#33]
1. I've opened my notes that's 100 KBytes file;
2. I've enabled panel - everything's OK;
3. Forgot to disable panel and opened 300 MByte file - NOK, NP++ hangs 'cause panel tries to render it in Markdown.

It would be nice if panel would hide on every opened file. Another way is add an ability to "cancel" rendering on "Show panel" hotkey

**Comment by mohzy83** [comment]
@PetbkA cloud you please check if the new function "automatically open panel for supported file types" helps you with this issue?
Furthermore when you restrict the supported file type via "Supported File Extension" markdown file should not be that large (300MByte).

**Comment by PetbkA** [comment]
**0.7.0 x64** - works OK. Thank you!

Should also note that if I disable automatic activation of panel, panel will spent 2 or 3 seconds before showing
![notepad++_2022-12-11_12-25-06](https://user-images.githubusercontent.com/22843816/206896163-36318460-dbfd-4a90-9f2b-5019305a461f.png)

on unsupported extensions. Guess it can't be faster 'cause this time is being spent on rendering this message
