### ISSUE TITLE
Zoom Level Limit

### ISSUE THREAD

**Issue by ballietf** [mohzy83/NppMarkdownPanel#35]
Great plug-in! Request: I use a an Ultrawide monitor (5120x1440). The Zoom Level limit of 200 is not enough. Can this limit be raised. Image 1, attached, is the Zoom level at 200 (the current max). Image 2 is the Zoom level after I've zoomed with my mouse wheel 18 wheel clicks.
![Markdown Panel Zoom Level 200](https://user-images.githubusercontent.com/43211530/98471403-f2235400-21b9-11eb-9b86-85d7ff8cd77b.jpg)
![Markdown Panel Zoom Level 18 mouse wheel clicks](https://user-images.githubusercontent.com/43211530/98471408-f7809e80-21b9-11eb-8443-a0f9b532b688.jpg)

**Comment by TailendWong** [comment]
Great plug-in! Great Issue! The difference is, I want a lower zoom level, 90 is not enough. I tried to change the zoomLevel in "X:\npp.7.9.1.portable\plugins\Config\nppmarkdownpaner.ini " ("X:\npp.7.9.1.portable" is the home of my notepad++), but it didn't work. I can't find the scope limitation of zoomLevel in your source code, but my level is limited. I think it would be better if this range were flexible, thank you.

[readable for Chinese]伟大的插件！不同的是，我想要更低的缩放级别，90不够。我尝试修改"X:\npp.7.9.1.portable\plugins\Config\NppMarkdownPanel.ini"中的zoomLevel，但没有用。我在你的源码中没有找到关于zoomLevel的范围限制，是我水平有限。我认为这个范围是灵活的会更好，谢谢。

**Comment by mohzy83** [comment]
this was enhanched in version 0.6.1
You can choose a zoomlevel from 40% to 400%.
