### ISSUE TITLE
Settings dialogue not showing HTML output or toolbar options

### ISSUE THREAD

**Issue by jack-sprat** [mohzy83/NppMarkdownPanel#38]
NppMarkdownPanel 0.5.0 with Npp 7.9.1, running on Win10, with .NET 4.7.1

The CSS file config and Zoom Level slider are visible in the Settings dialogue, but HTML output config, and toolbar checkbox are missing.

![NPP_mdPanel050Settings](https://user-images.githubusercontent.com/35769425/108439148-9fd9e080-7248-11eb-9162-28b20598f44c.PNG)

Great plug-in - I've recently come to prefer NppMdPanel over MdViewer++ as the rendering is more reliable, and I've found workarounds for the (current) lack of HTML and PDF export options (I use View Source then save as HTML, and Print Preview then Print to PDF). 

thanks for the great work on a really useful tool - JS

P.S. I guess that it's because the rendering is IE11 that context menu > View Source defaults to Notepad.exe rather than Npp.

**Comment by jack-sprat** [comment]
I see that this is fixed in [Vin's World 0.6.2.1 branch](https://github.com/vinsworldcom/NppMarkdownPanel/tree/0.6.2.1)

**Comment by mohzy83** [comment]
fixed in version 0.6.1
