### ISSUE TITLE
Line separator --- will break all following # header font emphasising

### ISSUE THREAD

**Issue by MetaChuh** [mohzy83/NppMarkdownPanel#4]
hi @mohzy83 

thanks for your new NppMarkdownPanel markdown viewer plugin.
i've just tested it and found two little issues:

* if you use the line separator `---` all following `#` h-lines will not be emphasised in font size.

* a `#` h-lines is always seen as underlined, instead of just emphasising the size.

**sample code to reproduce:**
```
## test 1

---

## test 2

---

### test 3
```

**sample result images:**

current view (NppMarkdownPanel):
![Imgur](https://i.imgur.com/XJCXCyG.png)

expected view (MarkdownViewer++):
![Imgur](https://i.imgur.com/PFVPwcT.png)

ps: i really like your new plugin, because it scales `![image name](image.url)` images at your markdown panel. 👍
(MarkdownViewer++ for example, keeps images 1:1 in size, cutting off larger images at the right edge, while NppMarkdownPanel is able to display the scaled, whole picture)

many thanks for your work.

greetings and best regards,
metachuh

**Comment by mohzy83** [comment]
Hi @MetaChuh,

I am happy you like my plugin. One of the reasons why I made this plugin, was to have a better HTML rendering engine than MarkdownViewer++. My plugin is using an embedded IE11 and the results are better compared to the HtmlRenderer-lib which is used by MarkdownViewer++. Thats why your images are scaled correctly ;)

The issue you have mentioned is related to CommonMark.NET. I will check if i can fix that in CommonMark.NET or if I have change to another c# MarkDown renderer library.

Best Regards,
Mohzy

**Comment by mohzy83** [comment]
So this was a style problem.
Fixed and tested with new release verison 0.3.0.

**Comment by MetaChuh** [comment]
very cool, thanks, i've just tried it out. 👍
i've seen you've already made the plugin list pull request too. 👍
let's hope it gets merged before the 7.6.5 release.

greetings and best regards,
metachuh
