### ISSUE TITLE
Icon not visible with Notepad++ dark theme

### ISSUE THREAD

**Issue by dartraiden** [mohzy83/NppMarkdownPanel#40]
Notepad++ v8.0 introduced the possibility for a dark ui-theme.  Plugin authors need to call `NPPM_ADDTOOLBARICON_FORDARKMODE` instead of `NPPM_ADDTOOLBARICON` for Notepad++ v8.0 or newer. 

https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9928

**Comment by mohzy83** [comment]
Fixed in version 0.6.1
Icon is now visible in dark mode.
