### ISSUE TITLE
[Feature Request] YAML and Code Block Syntax Highlighting

### ISSUE THREAD

**Issue by whoibrar** [mohzy83/NppMarkdownPanel#46]
## **Context :**
- [Front Matter](https://jekyllrb.com/docs/front-matter/) is added to `.md` files by Jekyll and many other services 
- 

## **Request :**
- Render with Syntax Highlighting for
  - YAML in FrontMatter
  - And Code Blocks 

## **Images:**
Left Side Source File 
Right Side Rendered View

### How it is looks in Obsidian
![Obsidian](https://i.imgur.com/H5rLqmG.png)

### How it is looks in NPP
![NPP](https://i.imgur.com/9xjI7fz.png)

## **Issue**

- Without proper syntax highlighting it breaks the format for YAML 
- The code blocks are hard to read

**Comment by 914802951** [comment]
I used highlight.js but it doesn't work in NPP, it can only be converted to html and read in Chrome.😒

**Comment by vinsworldcom** [comment]
Possible solution is to use Markdig extension [markdown-colorcode](https://github.com/wbaldoumas/markdown-colorcode) which uses [ColorCode-Universal](https://github.com/CommunityToolkit/ColorCode-Universal).

Seems pretty simple to just add to the pipeline in 'nppMarkdownPanel\MarkdigWrapper\MarkdigMarkdownGenerator.cs'
```C#
27:         public string ConvertToHtml(string markDownText, string filepath)
28:         {
29:             var pipeline = new MarkdownPipelineBuilder()
30:                 .UseAdvancedExtensions()
+                   .UseColorCode() 
31:                 .UsePreciseSourceLocation()
32:                 .Build();
```

Then just having to figure out how to include in the build and distribute the proper assemblies.

Cheers.

**Comment by mohzy83** [comment]
That sounds straightforward.
I will add the ColorCode lib for the next release.

**Comment by mohzy83** [comment]
This feature is now partly implemented in version 0.7.0.
Fenced code blocks will be highlighted.
![grafik](https://user-images.githubusercontent.com/26003088/206860457-f17b85d6-cfef-469a-96e4-5bf6b8f13d62.png)
becomes:
![grafik](https://user-images.githubusercontent.com/26003088/206860475-4e150341-078c-4428-b5c2-94dd110e98f1.png)

The markdig extension https://github.com/RichardSlater/Markdig.SyntaxHighlighting is being used.

The parsing of the Frontmatter block (with YAML) needs more investigation.
By default markdig will remove that block from the output, when using `new MarkdownPipelineBuilder().UseYamlFrontMatter()`.
Maybe it can be converted to a standard "code block", but that has to be implemented.

**Comment by mohzy83** [comment]
In version 0.7.1
YAML Frontmatter blocks are rendered as standard code blocks (no syntax highlighting yet).
![grafik](https://user-images.githubusercontent.com/26003088/209696943-f9c7687e-a26e-4b82-b01f-ec49cbcf60c4.png)
![grafik](https://user-images.githubusercontent.com/26003088/209697007-cd01eed0-e511-4e68-acbf-a511cca5f7bb.png)

**Comment by mohzy83** [comment]
closing this issue in favor of a new issue, concerning the support of further languages
