### ISSUE TITLE
[bug] cannot display non-ascii-characters

### ISSUE THREAD

**Issue by biggaeh** [mohzy83/NppMarkdownPanel#47]
Hi,

non-ascii-characters (èöäüß) are displayed as 1e8H5bX (diamond with questionmark). Have I missed a configuration item or is there a problem with utf-8 support?

Cheers
Birger

**Comment by biggaeh** [comment]
The problem was caused by the .md file being an ANSI file. After converting that file to UTF-8 everything was fine.
Sorry for the fuss.

**Comment by dartraiden** [comment]
Can you please fix this bug?

How to reproduce:
* Disable encoding auto-detection in N++ settings
* Create ASCII .md with non-ASCII symbols (see attached file as an example)
[example.md](https://github.com/mohzy83/NppMarkdownPanel/files/12135220/example.md)

Result: Notepad++ correctly shows non-ASCII symbols while the plugin shows them incorrectly.
