### ISSUE TITLE
NppMarkdownPanel is not support Chinese

### ISSUE THREAD

**Issue by ljhmily** [mohzy83/NppMarkdownPanel#48]
![image](https://user-images.githubusercontent.com/20486958/187823368-fef52834-ff68-4050-a55c-fe17a3d5a0eb.png)
when i save my text as html，all Chinese comes to ？？？。

**Comment by mohzy83** [comment]
known issue will be fixed in the next release

**Comment by mohzy83** [comment]
This issue is resolved with version 0.7.0
