### ISSUE TITLE
~~must be striked out~~

### ISSUE THREAD

**Issue by sergushenkov** [mohzy83/NppMarkdownPanel#5]
Text between two tildes (~~text~~) should appear as strikethrough. But in the Markdown panel is displayed the same \~\~text~~

**Comment by mohzy83** [comment]
Hi this is related to CommonMark.NET

**Comment by mohzy83** [comment]
Fixed and tested with new release 0.4.0.
Now the plugin is using Markdig, which supports the strikethrough syntax
