### ISSUE TITLE
Zoom level default and range too small for HD displays 

### ISSUE THREAD

**Issue by paulmoloneyr3** [mohzy83/NppMarkdownPanel#50]
On a Windows 11 laptop with a 3456 x 2160 display, the 100% zoom level is too small to read at all, and even at 400% the text is still too small to read comfortably. Would be good if either the zoom level takes account of the custom system scaling or even if the maximum zoom level is made higher.

**Comment by mohzy83** [comment]
Max. zoom level was increased to 800% in version 0.7.0.
Please check the new zoom level with your setup.
