### ISSUE TITLE
url links on the About dialog aren't clickable

### ISSUE THREAD

**Issue by BdR76** [mohzy83/NppMarkdownPanel#51]
Pretty cool plug-in, just wanted to post a minor issue though:

On the About form, the links aren't clickable and you also can't select and copy the text.
The only way to open them is open a separate notepad and type them in by hand.
You could turn it into a regular dialog form and use LinkLabels for the clickable links.

**Comment by mohzy83** [comment]
In version 0.7.0 you can copy the text and links in the about dialog.
