### ISSUE TITLE
Update Markdig for new features

### ISSUE THREAD

**Issue by BattleMage** [mohzy83/NppMarkdownPanel#54]
Update Markdig to latest version to support new features like Diagram and Figure support.

**Comment by mohzy83** [comment]
I will try to upgrade markdig for the next release

**Comment by mohzy83** [comment]
I added the new markdig version 0.30.4 in release 0.7.0.
@BattleMage , I could not find the diagram support, you mentioned, on markdigs feature list https://github.com/xoofx/markdig
What feature do you mean?

**Comment by BattleMage** [comment]
The feature is called **Diagrams** and [documented  here](https://github.com/xoofx/markdig/blob/master/src/Markdig.Tests/Specs/DiagramsSpecs.md)

Thanks a lot for updating that fast!

**Comment by mohzy83** [comment]
The feature is actually included when using the switch `UseAdvancedExtensions()`
The issure seems to be resolved then.
