### ISSUE TITLE
Code fences not rendered unless language label is in `ColorCode.Languages` dictionary (v0.7.0 regression)

### ISSUE THREAD

**Issue by rdipardo** [mohzy83/NppMarkdownPanel#55]
Since 9ebbb73, code fences with a language label other than `csharp`, `cplusplus`, `aspx`, etc., are not rendered at all. Any other language label has to be edited out.

## v0.7.0

![nppMrkdPanel-v0 7 0](https://user-images.githubusercontent.com/59004801/206824405-76e9a932-ab9b-483c-bf8f-a0ce13b676a7.gif)

## v0.6.2

![nppMrkdPanel-v0 6 2](https://user-images.githubusercontent.com/59004801/206824430-8cba514d-a52e-4bdf-95f4-3c1cefa1ea52.gif)

There needs to be a default case handler in [`Markdig.SyntaxHighlighting.LanguageTypeAdapter.Parse`][0], so that code fences are always rendered, even if the label is unrecognized.

[0]: https://github.com/mohzy83/NppMarkdownPanel/blob/9ebbb7325f7b39d49fd7138f7755ee8355cf1030/MarkdigWrapper/LanguageTypeAdapter.cs#L12

**Comment by mohzy83** [comment]
This issue has already been posted in 2020 see: https://github.com/RichardSlater/Markdig.SyntaxHighlighting/issues/16
Great that you found a solution!
I will merge the PR.
