### ISSUE TITLE
Plugin "Failed to load"

### ISSUE THREAD

**Issue by ma-schroeder** [mohzy83/NppMarkdownPanel#57]
Hi there,
i'm using the portable version of Notepad++ 8.4.7 and i cannot load your plugin in version 0.7.0. The old version 0.6.2 worked without problems. I tried a fresh install with npp.8.4.7.portable.x64.zip and NppMarkdownPanel-0.7.0.0-x64.zip and i get the following error:

![image](https://user-images.githubusercontent.com/11662301/207066274-a637aade-0b63-44d6-9209-79833135ac7f.png)

After closing Notepad++ the following is shown:

![image](https://user-images.githubusercontent.com/11662301/207066500-9ea8f52b-700a-4f49-b3ad-08d1ee51692d.png)

I think it has to do with the Windows LTSC-Version, see Debug Info:
```
Notepad++ v8.4.7   (64-bit)
Build time : Nov  1 2022 - 23:31:11
Path : C:\Software\npp_test\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise LTSC 2019 (64-bit) 
OS Version : 1809
OS Build : 17763.3650
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
```

On my private computer with Windows 10 Home and an installed Notepad++ (not portable) the new plugin version does work without problems:
```
Notepad++ v8.4.7   (64-bit)
Build time : Nov  1 2022 - 23:31:11
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 22H2
OS Build : 19045.2311
Current ANSI codepage : 1252
Plugins : 
    BetterMultiSelection (1.5)
    Explorer (1.9.5)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppMarkdownPanel (0.7)
```

Went back to version 0.6.2 for now. Maybe you can identify a cause for this issue. Would be great to use the new version with dark mode. Really appreciate your helpful plugin.

Thanks

**Comment by mohzy83** [comment]
Hi,
I have changed the way how the markdig assembly gets loaded in Version 0.7.0.
Maybe this causes the problem with the portable version of npp.
Have to admit I didn't test the plugin with npp portable.
Need to check that...

**Comment by ma-schroeder** [comment]
Hi,
i just tried the portable version and plugin 0.7.0 on my private computer and there it works. Debug Info from that:
```
Notepad++ v8.4.7   (64-bit)
Build time : Nov  1 2022 - 23:31:11
Path : D:\Temp\npp.8.4.7.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 22H2
OS Build : 19045.2311
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppMarkdownPanel (0.7)
```

So i think it has to do with the Windows LTSC 1809. Maybe some of the new libs are not compatible with the long term Windows version?

**Comment by ma-schroeder** [comment]
Hi,
under Control Panel > Programs and Features it lists version 6.0.2:

![image](https://user-images.githubusercontent.com/11662301/207284159-f8e3e1e5-3be2-40c9-9f48-53e9176757e2.png)

Registry tells me something about version 4.8.03761 which is confusing. So i just downloaded the installer for version 4.5.2 and it tells me it is already installed:

![image](https://user-images.githubusercontent.com/11662301/207286124-e98ed538-f4ed-432d-aec1-2e74401087dc.png)

Thanks

**Comment by mohzy83** [comment]
The .NET (classic) Version is 4.8, which should work without problems. Don't think thats the cause of your issue.
I thinks i have to improve the errorhandling, in the case the markdig lib (and also the wrapper) cannot be found.

**Comment by vinsworldcom** [comment]
For what it's worth, I've been using my version and the version I'm issuing pull request from on my Win10 64-bit computer on 2 separate instances of Notepad++ 8.4.7 portable with no issues on either.  My Control Panel => Programs and Features show:

![image](https://user-images.githubusercontent.com/9657169/207901776-ccf2be6f-a5ba-4a8a-a2e8-913a83d74761.png)

Cheers.

**Comment by mohzy83** [comment]
> For what it's worth, I've been using my version and the version I'm issuing pull request from on my Win10 64-bit computer on 2 separate instances of Notepad++ 8.4.7 portable with no issues on either. 

What kind of Windows 10 version is installed on your machine? The bug seems to appare on Windows LTSC 1809.

**Comment by mohzy83** [comment]
@ma-schroeder, could you please try this debug release and if there is still an error?
[NppMarkdownPanel-0.7.0.1-x64.zip](https://github.com/mohzy83/NppMarkdownPanel/files/10238480/NppMarkdownPanel-0.7.0.1-x64.zip)

**Comment by vinsworldcom** [comment]
> > For what it's worth, I've been using my version and the version I'm issuing pull request from on my Win10 64-bit computer on 2 separate instances of Notepad++ 8.4.7 portable with no issues on either.
> 
> What kind of Windows 10 version is installed on your machine? The bug seems to appare on Windows LTSC 1809.

![image](https://user-images.githubusercontent.com/9657169/207905109-ad2ef2f0-cc4f-4c8a-924f-c257639cf44e.png)

**Comment by ma-schroeder** [comment]
> @ma-schroeder, could you please try this debug release and check if there is still an error? [NppMarkdownPanel-0.7.0.1-x64.zip](https://github.com/mohzy83/NppMarkdownPanel/files/10238480/NppMarkdownPanel-0.7.0.1-x64.zip)

Hi there,
with this version Notepad++ starts and shows no error, this is the Debug Info:
```
Notepad++ v8.4.7   (64-bit)
Build time : Nov  1 2022 - 23:31:11
Path : C:\Software\npp_test\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise LTSC 2019 (64-bit) 
OS Version : 1809
OS Build : 17763.3650
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppMarkdownPanel (0.7.0.1)
```

But i do get an error when i open a .md-file. The Markdown Panel looks like this:

![image](https://user-images.githubusercontent.com/11662301/208033086-f712d817-183d-449c-a439-cdf06a4eb984.png)

Text:
```
Error loading MarkdigWrapper from path C:\Software\npp_test\plugins\NppMarkdownPanel\lib\MarkdigWrapper.dll.
Exception: Die Datei oder Assembly "file:///C:\Software\npp_test\plugins\NppMarkdownPanel\lib\MarkdigWrapper.dll"
oder eine Abhängigkeit davon wurde nicht gefunden.
Der Vorgang wird nicht unterstützt. (Ausnahme von HRESULT: 0x80131515) 
```

**Comment by vinsworldcom** [comment]
Please provide a directory listing of the files in C:\Software\npp_test\plugins\NppMarkdownPanel.

From "Command Prompt" (cmd.exe):
```
dir /s
```

From "Powershell" (powershell.exe):
```
dir -Recurse
```

Cheers.

**Comment by ma-schroeder** [comment]
Hi,

```
U:\>c:

C:\>cd C:\Software\npp_test\plugins\NppMarkdownPanel

C:\Software\npp_test\plugins\NppMarkdownPanel>dir /s
 Datenträger in Laufwerk C: ist SYSTEM
 Volumeseriennummer: 4225-4436

 Verzeichnis von C:\Software\npp_test\plugins\NppMarkdownPanel

16.12.2022  06:57    <DIR>          .
16.12.2022  06:57    <DIR>          ..
16.12.2022  06:57    <DIR>          help
16.12.2022  06:57    <DIR>          lib
15.02.2019  12:29             1.086 License.txt
15.12.2022  16:33           257.536 NppMarkdownPanel.dll
12.12.2022  09:53             6.239 README.md
08.12.2022  18:46             6.995 style-dark.css
17.04.2019  10:18             6.971 style.css
               5 Datei(en),        278.827 Bytes

 Verzeichnis von C:\Software\npp_test\plugins\NppMarkdownPanel\help

16.12.2022  06:57    <DIR>          .
16.12.2022  06:57    <DIR>          ..
08.12.2022  20:54            11.601 code-highlighting.png
04.12.2022  22:21           149.858 npp-preview-dm.png
15.02.2019  11:58            94.923 npp-preview.png
13.07.2019  10:38            14.597 open-settings.png
15.02.2019  12:08            20.300 pluginfolder.png
02.10.2020  21:29               464 save-btn.png
22.02.2019  10:48           975.169 sync_caret.gif
               7 Datei(en),      1.266.912 Bytes

 Verzeichnis von C:\Software\npp_test\plugins\NppMarkdownPanel\lib

16.12.2022  06:57    <DIR>          .
16.12.2022  06:57    <DIR>          ..
19.07.2016  21:47           115.712 ColorCode.dll
27.09.2022  07:30           460.800 Markdig.dll
15.12.2022  16:32            10.752 MarkdigWrapper.dll
19.02.2020  10:05            20.864 System.Buffers.dll
19.02.2020  10:05           137.088 System.Memory.dll
19.02.2020  10:05            16.768 System.Runtime.CompilerServices.Unsafe.dll
               6 Datei(en),        761.984 Bytes

     Anzahl der angezeigten Dateien:
              18 Datei(en),      2.307.723 Bytes
               8 Verzeichnis(se), 116.278.484.992 Bytes frei

C:\Software\npp_test\plugins\NppMarkdownPanel>
```

thanks

**Comment by rdipardo** [comment]
@ma-schroeder, repeat that directory listing like this:

    dir /S /R

Do you see hidden files with names like `NppMarkdownPanel.dll:Zone.Identifier:$DATA`?

If so, it means Windows [is blocking][0] the execution of the DLLs for security.

Right-click on each DLL and select *Properties*. If the *Unblock* option is shown, *un-select* the checkbox and click *Apply*, then *OK*.

  <img src="https://i.ibb.co/C77Wmfx/NPPFSIPlugin-MOTW.png" alt="NPPFSIPlugin-MOTW" border="0" width="425"/>

[0]: https://www.bitdefender.com/blog/hotforsecurity/7-zip-now-supports-windows-mark-of-the-web-security-feature/#:~:text=Windows%20automatically%20adds%20Mark%2Dof%2Dthe%2DWeb%2C%20a%20%E2%80%98Zone.Id%E2%80%99%20alternate%20data%20stream%20to%20downloaded%20files.

**Comment by ma-schroeder** [comment]
Oh wow, you are absolutely right. Thanks for the link and the info. I use 7-zip 22.01 and the setting "Propagate Zone.Id stream" is set to "Yes" on my work laptop. On my home pc this setting is set to "No".

Here is the output:
```
U:\>c:

C:\>cd C:\Software\npp_test\plugins\NppMarkdownPanel

C:\Software\npp_test\plugins\NppMarkdownPanel>dir /S /R
 Datenträger in Laufwerk C: ist SYSTEM
 Volumeseriennummer: 4225-4436

 Verzeichnis von C:\Software\npp_test\plugins\NppMarkdownPanel

16.12.2022  06:57    <DIR>          .
16.12.2022  06:57    <DIR>          ..
16.12.2022  06:57    <DIR>          help
16.12.2022  06:57    <DIR>          lib
15.02.2019  12:29             1.086 License.txt
                                650 License.txt:Zone.Identifier:$DATA
15.12.2022  16:33           257.536 NppMarkdownPanel.dll
                                650 NppMarkdownPanel.dll:Zone.Identifier:$DATA
12.12.2022  09:53             6.239 README.md
                                650 README.md:Zone.Identifier:$DATA
08.12.2022  18:46             6.995 style-dark.css
                                650 style-dark.css:Zone.Identifier:$DATA
17.04.2019  10:18             6.971 style.css
                                650 style.css:Zone.Identifier:$DATA
               5 Datei(en),        278.827 Bytes

 Verzeichnis von C:\Software\npp_test\plugins\NppMarkdownPanel\help

16.12.2022  06:57    <DIR>          .
16.12.2022  06:57    <DIR>          ..
08.12.2022  20:54            11.601 code-highlighting.png
                                650 code-highlighting.png:Zone.Identifier:$DATA
04.12.2022  22:21           149.858 npp-preview-dm.png
                                650 npp-preview-dm.png:Zone.Identifier:$DATA
15.02.2019  11:58            94.923 npp-preview.png
                                650 npp-preview.png:Zone.Identifier:$DATA
13.07.2019  10:38            14.597 open-settings.png
                                650 open-settings.png:Zone.Identifier:$DATA
15.02.2019  12:08            20.300 pluginfolder.png
                                650 pluginfolder.png:Zone.Identifier:$DATA
02.10.2020  21:29               464 save-btn.png
                                650 save-btn.png:Zone.Identifier:$DATA
22.02.2019  10:48           975.169 sync_caret.gif
                                650 sync_caret.gif:Zone.Identifier:$DATA
               7 Datei(en),      1.266.912 Bytes

 Verzeichnis von C:\Software\npp_test\plugins\NppMarkdownPanel\lib

16.12.2022  06:57    <DIR>          .
16.12.2022  06:57    <DIR>          ..
19.07.2016  21:47           115.712 ColorCode.dll
                                650 ColorCode.dll:Zone.Identifier:$DATA
27.09.2022  07:30           460.800 Markdig.dll
                                650 Markdig.dll:Zone.Identifier:$DATA
15.12.2022  16:32            10.752 MarkdigWrapper.dll
                                650 MarkdigWrapper.dll:Zone.Identifier:$DATA
19.02.2020  10:05            20.864 System.Buffers.dll
                                650 System.Buffers.dll:Zone.Identifier:$DATA
19.02.2020  10:05           137.088 System.Memory.dll
                                650 System.Memory.dll:Zone.Identifier:$DATA
19.02.2020  10:05            16.768 System.Runtime.CompilerServices.Unsafe.dll
                                650 System.Runtime.CompilerServices.Unsafe.dll:Zone.Identifier:$DATA
               6 Datei(en),        761.984 Bytes

     Anzahl der angezeigten Dateien:
              18 Datei(en),      2.307.723 Bytes
               8 Verzeichnis(se), 116.272.820.224 Bytes frei

C:\Software\npp_test\plugins\NppMarkdownPanel>
```

After right-clicking each DLL and explicitly "allowing" an access i'm now able to use the plugin, yeah. The properties of each DDL locked like this:
![image](https://user-images.githubusercontent.com/11662301/208110681-8969e14f-905c-4c26-9974-9723866fd59d.png)

So i had to mark the "Zulassen" (Allow) checkbox and hit OK. The additinal Zone.Identifier:$DATA files are now gone in the lib directory and the plugin is working.

![image](https://user-images.githubusercontent.com/11662301/208111516-221361c6-2eda-4dc0-8c29-883fbda28d00.png)


Thank you!

**Comment by rdipardo** [comment]
> Thank you!

No problem. It once [happened to me] as well.

[happened to me]: https://github.com/oleg-shilo/cs-script.npp/issues/64#issuecomment-1046114822

**Comment by mohzy83** [comment]
Big Thanks to @rdipardo for helping with this issue !
I wonder why the plugin itself (NppMarkdownPanel.dll) was not blocked in the first place ?

**Comment by JiCiT** [comment]
Wow!  Huge thanks.  Should have known it was something like.  This issue's details probably saved me a few hours worth of frustration.

**Comment by mattcheau** [comment]
@ChrisTorng This comes up all the time. [PowerShell instructions here](https://github.com/mohzy83/NppMarkdownPanel/issues/120#issuecomment-2993595814).
