### ISSUE TITLE
Fails to pick up Dark Mode in Npp

### ISSUE THREAD

**Issue by Darthagnon** [mohzy83/NppMarkdownPanel#70]
## Bug: 
Plugin fails to apply style-dark.css when dark mode is enabled in Npp (v8.2, 32 bit)

As a workaround I just set the default stylesheet to the dark one, but it isn't detecting the switch within Npp. I'll post back after a PC restart, maybe that will fix it.

Win10 v1709

**Comment by rautamiekka** [comment]
1709 has been dead for almost 3y ...

**Comment by mohzy83** [comment]
The plugin detects the dark mode with an API which was added in version 8.4.1 of NPP.
See here: https://npp-user-manual.org/docs/plugin-communication/#nppm-isdarkmodeenabled
Means dark mode support doesn't work with version 8.2 
Is it possible for you to upgrade you npp version?
![grafik](https://user-images.githubusercontent.com/26003088/209845984-894b2156-8f67-4838-89c9-3d9060ce90f4.png)

**Comment by Darthagnon** [comment]
> Is it possible for you to upgrade your npp version?
Done! All working perfectly now! Thank you! Would it be possible to add a note to the Readme, e.g. "automatic dark/light mode switching supported in NPP v8.4.1+"?

**Comment by mohzy83** [comment]
> Done! All working perfectly now! Thank you! 
Great!
> Would it be possible to add a note to the Readme, e.g. "automatic dark/light mode switching supported in NPP v8.4.1+, earlier versions require manual switching or setting `style-dark.css` as default"?
Sure I will add a note to the Readme.
