### ISSUE TITLE
[Question] run outside Npp

### ISSUE THREAD

**Issue by loukaspd** [mohzy83/NppMarkdownPanel#75]
this is not an issue but a question.
Is there a way to run the Viewer outside of Npp?

**Comment by mohzy83** [comment]
Hi, I am not sure what you mean.
Do you want to open the Viewer in a separate window (out of NPP)?

**Comment by loukaspd** [comment]
Hi, thanks for the reply,  
I want to be able to start the Viewer without even opening the NPP.  
Would that be possible?

**Comment by mohzy83** [comment]
Currently there is no Standalone version of (Npp)MarkdownPanel.
I think it should be possible to put the viewer in a separate executable, but that requires some fundamentally changes to the codebase. The codebase is tighly coupled to the N++ Plugininterface, it will be necessary to replace all those interfaces.

**Comment by pa-0** [comment]
I see that you have a branch (and folder) called standalone. How developed is that portion of the project?
