### ISSUE TITLE
Plugin release v0.7.2 searches help files in wrong directory

### ISSUE THREAD

**Issue by dinkumoil** [mohzy83/NppMarkdownPanel#76]
### Description

Release v0.7.2 of the plugin searches help files in folder `<Npp-folder>\plugins\MarkdownPanel` instead of `<Npp-folder>\plugins\NppMarkdownPanel`.

### Steps to Reproduce

1. Navigate to `(menu) Plugins -> MarkdownPanel` and click on menu item `Help`.
2. A message box with an error message appears:

![grafik](https://user-images.githubusercontent.com/24699812/218276797-ad79d330-10c2-46f9-9aef-221dd44393b9.png)

3. Afte creating folder `<Npp-folder>\plugins\MarkdownPanel` and moving folder `help` and file `README.md` from folder `<Npp-folder>\plugins\NppMarkdownPanel` to the new folder, help file is shown in _Notepad++_

**Comment by rdipardo** [comment]
The installation folder depends on the JSON manifest bundled with Plugins Admin, so this issue really belongs [**here**](https://github.com/notepad-plus-plus/nppPluginList/issues).

The help file path is built from the `PluginName` field; it's always in sync with the compiled assembly:

https://github.com/mohzy83/NppMarkdownPanel/blob/0fb200418d4ca871e962c5189f058f1dbb0e51bf/NppMarkdownPanel/MarkdownPanelController.cs#L214

**Comment by dinkumoil** [comment]
@rdipardo 

> this issue really belongs [here](https://github.com/notepad-plus-plus/nppPluginList/issues).

I don't agree. The plugin's DLL name is `NppMarkdownPanel.dll`, thus the folder it is stored into **must** be `<Npp-folder>\plugins\NppMarkdownPanel`. This should also be the folder where plugin's companion files and folders are stored. It seems like function `Main.PluginName` returns the string `MarkdownPanel` instead of `NppMarkdownPanel`, so the plugin searches it help files in the wrong folder.

I guess the bug derives from recent renaming of the plugin's menu entry from `NppMarkdownPanel` to `MarkdownPanel` in commit 9872e9f. When installing a plugin, _PluginAdmin_ generates the target folder name from the name of the DLL file it finds at the root level of the plugin's ZIP package, not from the return value of plugin interface's function `getName`, simply because the plugin is not (an can not be) loaded during its installation.

**Comment by rdipardo** [comment]
> The plugin's DLL name is `NppMarkdownPanel.dll`

I [stand corrected](https://github.com/mohzy83/NppMarkdownPanel/blob/master/NppMarkdownPanel/NppMarkdownPanel.csproj#L10). It seems that 9872e9f just changed the value of an internal class member. To really keep the help file path in sync, you would have to extract the directory name from the assembly's binary file information; something like this:

~~~diff
diff --git a/NppMarkdownPanel/MarkdownPanelController.cs b/NppMarkdownPanel/MarkdownPanelController.cs
index 5e37268..57c600f 100644
--- a/NppMarkdownPanel/MarkdownPanelController.cs
+++ b/NppMarkdownPanel/MarkdownPanelController.cs
@@ -8,6 +8,7 @@ using System.Drawing.Imaging;
 using System.IO;
 using System.Linq;
 using System.Runtime.InteropServices;
+using System.Diagnostics;
 using System.Text;
 using System.Threading.Tasks;
 using System.Windows.Forms;
@@ -209,9 +210,12 @@ namespace NppMarkdownPanel

         private void ShowHelp()
         {
+            var dll = (typeof(Main)).Assembly;
+            var dllVersionInfo = FileVersionInfo.GetVersionInfo(dll.Location);
+            string dllDir = Path.GetFileNameWithoutExtension(dllVersionInfo.OriginalFilename);
             StringBuilder sbPluginPath = new StringBuilder(Win32.MAX_PATH);
             Win32.SendMessage(PluginBase.nppData._nppHandle, (uint)NppMsg.NPPM_GETPLUGINHOMEPATH, Win32.MAX_PATH, sbPluginPath);
-            var helpFile = Path.Combine($"{sbPluginPath}", Main.PluginName, "README.md");
+            var helpFile = Path.Combine($"{sbPluginPath}", dllDir, "README.md");
             Win32.SendMessage(PluginBase.nppData._nppHandle, (uint)NppMsg.NPPM_DOOPEN, 0, helpFile);
             if (!isPanelVisible)
                 TogglePanelVisible();

~~~

**Comment by mohzy83** [comment]
Like @rdipardo said, the const ``Main.PluginName`` is used to construct the path to the help file.
It's much safer to use the directory of the executing assembly and dont rely on that constant.
I will change the implementation accordingly.

**Comment by mohzy83** [comment]
fixed in version 0.7.3. @dinkumoil please verify. Thanks.

**Comment by rdipardo** [comment]
It works.

<img width="958" alt="nppMrkdPnl-2023-02-19-152121" src="https://user-images.githubusercontent.com/59004801/219973354-24a3d681-7f07-4bbf-ba2d-39ed704ca686.png">

**Comment by dinkumoil** [comment]
> It works.

Confirmed.
