### ISSUE TITLE
Error on execution in Markdown Panel.

### ISSUE THREAD

**Issue by hkdemiralp** [mohzy83/NppMarkdownPanel#85]
As soon as I type anything in a md file, Markdown Panel gives this error message:
`Error executing ConvertToHtml. Exception: Exception has been thrown by the target of an invocation. `

## Info:
Notepadd++: v8.5.4 (64bit)
Markdown Panel: v0.7.3
OS: Windows 11 Pro (22H2)

**Comment by mohzy83** [comment]
Please check Issue https://github.com/mohzy83/NppMarkdownPanel/issues/57 
Maybe your problem is somehow related.
