### ISSUE TITLE
Unable to display special characters

### ISSUE THREAD

**Issue by dderp** [mohzy83/NppMarkdownPanel#89]
The preview can't display special characters like ä, é, ‘, or ’. This seems to be a font issue, considering other markdown viewers can show these characters.

**Comment by mohzy83** [comment]
Please provide a sample file for further investigation of this issue.

**Comment by dderp** [comment]
Just turn on the preview and you'll see what I'm talking about.
[Sample file.md](https://github.com/mohzy83/NppMarkdownPanel/files/12937702/Sample.file.md)

**Comment by mohzy83** [comment]
This seems to be an encoding problem in n++.
With plain ANSI it looks like this:
![grafik](https://github.com/mohzy83/NppMarkdownPanel/assets/26003088/eb1b27a3-72e8-406c-95ec-94a257508fd5)

But when I select an encoding like ISO-8859-1 everything looks fine:
![grafik](https://github.com/mohzy83/NppMarkdownPanel/assets/26003088/ac7d7cb8-f775-4aef-9c67-2e1bdb7fb790)
![grafik](https://github.com/mohzy83/NppMarkdownPanel/assets/26003088/9b6e7afc-4b3d-4045-a8f5-040063842281)

**Comment by dderp** [comment]
Ah, that would explain it. My bad, I guess... For me, the stuff on the left still shows up properly even without specifically choosing a Western European encoding.
