### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by eeucalyptus** [mohzy83/NppMarkdownPanel#9]
Hi,
I use this plugin on a daily basis, but one thing that bothers me is the style. I would like to customize some CSS properties, eg. line height, margin, etc. Would it be possible to outsource the CSS file to the plugin directory?
Thanks in advance.

**Comment by mohzy83** [comment]
I merged ur PR and update release powershell script to include the style.css in the release zip files.

**Comment by MuhdNurHidayat** [comment]
Thank you so much for this feature!

I know it's not actually released yet but I just grab latest source and build a copy myself in visual studio for my x86 notepad++ and it worked as I expected...

Finally a markdown preview plugin I can properly use custom CSS with!!

Note that I did tried MarkdownViewer++ but it didn't display my custom CSS corectly unlike this (pre-release version) plugin and idk why...

Looking forward to official release of new version...
