### ISSUE TITLE
Always render fenced code blocks (solved)

### ISSUE THREAD

**Issue by realjck** [mohzy83/NppMarkdownPanel#98]
### ✔ Right now, it's possible to render some highlighted fenced code blocks with this syntax:

\```js
   doCodeBlock()=>{
       console.log('code block');
  }
\```
```js
  doCodeBlock()=>{
  	console.log('code block');
  }
```

### ✔ It works also without specifying the language:

\```
this is code block
\```
```
this is code block
```

### ❌ But this one doesn't work, the result is the text on one line unformatted:
\```bash
git commit -m "feat: code block"
\```
git commit -m "feat: code block" 

**Also this obviously lead to an unformatted line:**

\```abc
This should be some code block
\```
This should be some code block 

---

I haven't looked at whether it's possible to configure the languages, but I think it would be wise that as soon as quotes are used, then the code block is always rendered by default.

**Comment by mohzy83** [comment]
I have checked your issue with the current version of the plugin (0.7.3).
Everything seems to work fine, even with the "bash" language hint:
![grafik](https://github.com/mohzy83/NppMarkdownPanel/assets/26003088/99f18078-02aa-47c8-aaf9-9377c0edb08e)

**Comment by realjck** [comment]
I just tried on a clean install on another computer, and indeed, it works correctly.

I will investigate this evening or tomorrow why my installation poses this strange problem and keep you informed.

**Comment by realjck** [comment]
Indeed everything is OK on v0.7.3

For some reason, the version I installed was on an old version v0.7
Although I installed the plugin last week, my package manager was not updated on my side.
I should have investigated better from the start 🙄

This ticket can be closed.
Thank you and sorry for inconvenience.
